### ISSUE TITLE
Error when running Hoaxy config

### ISSUE THREAD

**Issue by vinaysetty** [IUNetSci/hoaxy-backend#64]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/hoaxy/bin/hoaxy", line 11, in <module>
    load_entry_point('hoaxy==0.1.0', 'console_scripts', 'hoaxy')()
  File "/home/ubuntu/anaconda2/envs/hoaxy/lib/python3.7/site-packages/hoaxy-0.1.0-py3.7.egg/hoaxy/commands/cmdline.py", line 122, in main
  File "/home/ubuntu/anaconda2/envs/hoaxy/lib/python3.7/site-packages/hoaxy-0.1.0-py3.7.egg/hoaxy/commands/config.py", line 94, in run
  File "/home/ubuntu/anaconda2/envs/hoaxy/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ubuntu/anaconda2/envs/hoaxy/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/.cache/Python-Eggs/hoaxy-0.1.0-py3.7.egg-tmp/hoaxy/data/samples/__pycache__'

**Comment by filmenczer** [comment]
@vinaysetty can you please provide more details? Which version have you installed, AWS or Docker?

**Comment by filmenczer** [comment]
Closing for now due to lack of information about version. Can reopen later if @vinaysetty sends further details.
